# Generated by Django 5.2.3 on 2025-07-13 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0002_iponotification_ipotracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('allotted', 'Allotted'), ('not_allotted', 'Not Allotted')], default='applied', max_length=20)),
                ('quantity_applied', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipo_app.ipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ipo')},
            },
        ),
        migrations.CreateModel(
            name='IPOReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField()),
                ('reminder_time', models.TimeField()),
                ('message', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipo_app.ipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ipo')},
            },
        ),
    ]
