# Generated by Django 5.2.3 on 2025-07-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0004_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
